apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: "first-pipeline"
  namespace: mlops  
spec:
  entrypoint: first-pipeline
  arguments:
    parameters:
    - {name: namespace, value: ""}  
  templates:
  - name: echo
    container:
      args: [echo "hello world"]
      command: [sh, -c]
      image: library/bash:4.4.23
      resources:               
        limits:
          memory: 32Mi
          cpu: 100m
  - name: first-pipeline
    dag:
      tasks:
      - {name: echo, template: echo}
      
  arguments:
    parameters: []
