apiVersion: kubedirector.hpe.com/v1beta1
kind: KubeDirectorApp
metadata:
  name: kd-rstudio-custom
spec:
  capabilities: []
  config:
    roleServices:
    - roleID: controller
      serviceIDs:
      - http
    selectedRoles:
    - controller 
  configSchemaVersion: 8
  distroID: kd-rstudio
  label:
    description: rstudio app
    name: kd-rstudio-custom
  logoURL: https://raw.githubusercontent.com/MissaouiAhmed/hpe-kd-image/81e85aaadc7c34035ff160dd61f004a3f61e95dd/rstudio.png
  roles:
  - cardinality: 1+
    configPackage:
      packageURL: file:///opt/configscript/appconfig.tgz
      useNewSetupLayout: false
    eventList:
    - configure
    - addnodes
    - delnodes
    id: controller 
    imageRepoTag: dockeridam/kdrstudio:latest
    minResources:
      cpu: '2'
      memory: 10Mi
    persistDirs:
    - /home
    - /data
  services:
  - endpoint:
      hasAuthToken: false
      isDashboard: true
      path: /
      port: 8787
      urlScheme: http
    id: http
    label:
      name: http
  systemdRequired: false
  version: '1'
