apiVersion: kubedirector.hpe.com/v1beta1
kind: KubeDirectorApp
metadata:
  labels:
    kubedirector.hpe.com/AIML_category: Notebook
  name: kd-nifi
spec:
  capabilities: []
  config:
    roleServices:
    - roleID: node
      serviceIDs:
      - http
    selectedRoles:
    - controller 
  configSchemaVersion: 8
  distroID: kd-nifi
  label:
    description: nifi app
    name: nifi
  logoURL: https://www.ambient-it.net/wp-content/uploads/2020/09/logo-apache-nifi-200x175-1.png
  roles:
  - cardinality: 1+
    configPackage:
      packageURL: https://github.com/MissaouiAhmed/hpe-kd-config/releases/download/refs%2Fheads%2Fmain/appconfig.tgz
    eventList:
    - configure
    - addnodes
    - delnodes
    id: controller 
    imageRepoTag: dockeridam/kdninfi:latest
    minResources:
      cpu: '2'
      memory: 10Mi
    persistDirs:
    - /home
    - /data
  services:
  - endpoint:
      hasAuthToken: false
      isDashboard: true
      path: /nifi
      port: 8080
      urlScheme: http
    id: http
    label:
      name: http
  systemdRequired: true
  version: '1'
